$schema: https://azuremlschemas.azureedge.net/preview/commandComponent.schema.json

name: openai-fine-tune

environment:
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
  conda_file: ./conda.yml

code:
  local_path: ./src/fine_tune

inputs:
  training_data:
    type: path

  validation_data:
    type: path
  
  model:
    type: string
    enum: [ada, babbage, curie, davinci]
    default: ada
  n_epochs:  
    type: integer
    default: 1
  batch_size: 
    type: integer
    default: 4
  learning_rate_multiplier: 
    type: number
    default: 0.1
  use_packing: 
    type: boolean
    default: true
  classification_n_classes: 
    type: integer
    default: 5

outputs:
  fine_tune_metadata:
    type: path
    
command: >-
  python fine_tune.py
    --training_data ${{inputs.training_data}}
    --validation_data ${{inputs.validation_data}}
    --model ${{inputs.model}}
    --n_epochs ${{inputs.n_epochs}}
    --batch_size ${{inputs.batch_size}}
    --learning_rate_multiplier ${{inputs.learning_rate_multiplier}}
    --use_packing ${{inputs.use_packing}}
    --classification_n_classes ${{inputs.classification_n_classes}}
    --fine_tune_metadata ${{outputs.fine_tune_metadata}}
    

