name: openai3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - scikit-learn
  - pip
  - pip:
    - mlflow<2.0.0
    - openai
    - azureml-mlflow
    - azureml-core
    - scipy
    - evaluate
    - langchain
    - matplotlib