$schema: https://azuremlschemas.azureedge.net/preview/pipelineJob.schema.json
type: pipeline

compute: azureml:cpu-cluster

jobs:
  process_data:
    type: command
    environment: 
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
      conda_file: ./conda.yml

    code:
      local_path: ./src/process_data

    inputs:
      raw_data: 
        dataset: azureml:yelp_raw:1
      prompt_column: text
      completion_column: stars
      train_test_split: 0.8
      seed: 172983

    outputs:
      train:
        mode: mount
      validation: 
        mode: mount

    command: >- 
      python process_data.py 
        --raw_data ${{inputs.raw_data}} 
        --prompt_column ${{inputs.prompt_column}}
        --completion_column ${{inputs.completion_column}}
        --train_output ${{outputs.train}} 
        --validation_output ${{outputs.validation}} 
        --seed ${{inputs.seed}}
        --train_test_split ${{inputs.train_test_split}}


  upload_data_train:
    type: command
    environment: 
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
      conda_file: ./conda.yml

    code:
      local_path: ./src/upload_data

    inputs:
      folder_to_upload: ${{jobs.process_data.outputs.train}}

    outputs:
      upload_metadata:

    compute: azureml:cpu-cluster

    command: >- 
      python upload_data.py 
        --folder_to_upload ${{inputs.folder_to_upload}} 
        --upload_metadata ${{outputs.upload_metadata}}

  upload_data_validation:
    type: command
    environment: 
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
      conda_file: ./conda.yml

    code:
      local_path: ./src/upload_data

    inputs:
      folder_to_upload: ${{jobs.process_data.outputs.validation}}

    outputs:
      upload_metadata:

    compute: azureml:cpu-cluster

    command: >- 
      python upload_data.py 
        --folder_to_upload ${{inputs.folder_to_upload}} 
        --upload_metadata ${{outputs.upload_metadata}}
  
  fine_tune:
    type: command
    environment:
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
      conda_file: ./conda.yml

    code:
      local_path: ./src/fine_tune

    inputs:
      training_data: ${{jobs.upload_data_train.outputs.upload_metadata}}

      validation_data: ${{jobs.upload_data_validation.outputs.upload_metadata}}
      
      model: ada
      n_epochs: 1
      batch_size: 4
      learning_rate_multiplier: 0.1
      use_packing: True
      classification_n_classes: 5

    outputs:
      fine_tune_metadata:
        
    command: >-
      python fine_tune.py
        --training_data ${{inputs.training_data}}
        --validation_data ${{inputs.validation_data}}
        --model ${{inputs.model}}
        --n_epochs ${{inputs.n_epochs}}
        --batch_size ${{inputs.batch_size}}
        --learning_rate_multiplier ${{inputs.learning_rate_multiplier}}
        --use_packing ${{inputs.use_packing}}
        --classification_n_classes ${{inputs.classification_n_classes}}
        --fine_tune_metadata ${{outputs.fine_tune_metadata}}
        
    compute: azureml:cpu-cluster

  save_model:
    type: command
    environment:
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
      conda_file: ./conda.yml

    code:
      local_path: ./src/save_model

    inputs:
      fine_tune: ${{jobs.fine_tune.outputs.fine_tune_metadata}}

    outputs:
      model:
        
    command: >-
      python save_model.py
        --fine_tune ${{inputs.fine_tune}}
        --model ${{outputs.model}}
        
    compute: azureml:cpu-cluster
